# Generated by Django 2.2.16 on 2022-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_email', models.EmailField(max_length=254)),
                ('confirmation_username', models.CharField(max_length=19)),
                ('confirmation_code', models.CharField(max_length=8)),
            ],
        ),
    ]
