# Generated by Django 2.2.16 on 2022-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_categorie_comment_genre_title_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationData',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='aasdasdad', max_length=8),
            preserve_default=False,
        ),
    ]
