# Generated by Django 2.2.16 on 2022-08-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220826_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='category_name',
        ),
        migrations.AddField(
            model_name='categorie',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Categorie'),
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', to='reviews.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=9, verbose_name='Role'),
        ),
    ]
